from implicitmodules.torch.Attachment.attachement import EnergyAttachement
from implicitmodules.torch.Attachment.attachement import GeomlossAttachement
from implicitmodules.torch.Attachment.attachement import L2NormAttachement
from implicitmodules.torch.Attachment.attachement import VarifoldAttachement
