from typing import Iterable

import torch

from imodal.Manifolds.Abstract import Manifold
from imodal.Manifolds.Landmark import Landmarks
from imodal.StructuredFields import StructuredField_m, StructuredField_0
from imodal.StructuredFields.Abstract import SumStructuredField


class CompoundLandmarks(Manifold):
    def __init__(self, dim, nbs_pts, gd=None, tan=None, cotan=None, device=None):
        
        # TODO check dimensions

        self.nbs_pts = nbs_pts
        super().__init__(((dim,), (dim,)), nbs_pts[0], gd, tan, cotan, device=device)
        self.manifolds = [Landmarks(dim, nbs_pts[0], device=device), Landmarks(dim, nbs_pts[1], device=device)]

        self.__dim = dim

    @property
    def dim(self):
        return self.__dim

    def inner_prod_field(self, field):
        return self.manifolds[0].inner_prod_field(field) + self.manifolds[1].inner_prod_field(field) 
    
    def infinitesimal_action(self, field):
        """Applies the vector field generated by the module on the landmarks."""
        
        tan0 = self.manifold[0].infinitesimal_action(field)
        tan1 = self.manifold[1].infinitesimal_action(field)
        
        return CompoundLandmarks(self.__dim, self.nbs_pts, gd=self.gd, tan=(tan0, tan1), device=self.device)

    def cot_to_vs(self, sigma, backend=None):
        v0 = StructuredField_0(self.gd[0], self.cotan[0], sigma, backend=backend)
        v1 = StructuredField_0(self.gd[1], self.cotan[1], sigma, backend=backend)
        
        return SumStructuredField([v0, v1])

