import numpy as np
from scipy.linalg import solve

import old.StructuredFields.StructuredFields_0
from old import GeometricalDescriptors, kernels as ker
from old.DeformationModules.DeformationModules import DeformationModule


class ElasticOrderO(DeformationModule):
    """
     Elastic module of order 0
    """
    
    def __init__(self, sigma, N_pts, dim, coeff, nu):
        """
        sigma is the scale of the rkhs of generated vector fields
        N_pts is the number of landmarks
        dim is the dimension of the ambient space
        """
        self.sig = sigma
        self.N_pts = N_pts
        self.dim = dim
        self.coeff = coeff
        self.nu = nu
        self.GD = old.GeometricalDescriptors.GD_landmark.GD_landmark(N_pts, dim)
        self.SKS = np.zeros([self.N_pts * self.dim, self.N_pts * self.dim])
        self.Mom = np.zeros([self.N_pts, self.dim])
        self.Cont = np.zeros([self.N_pts, self.dim])
        self.cost = 0.
    
    def copy(self):
        return ElasticOrderO(self.sig, self.N_pts, self.dim, self.coeff, self.nu)
    
    def copy_full(self):
        Mod = ElasticOrderO(self.sig, self.N_pts, self.dim, self.coeff, self.nu)
        Mod.GD = self.GD.copy_full()
        Mod.SKS = self.SKS.copy()
        Mod.Mom = self.Mom.copy()
        Mod.Cont = self.Cont.copy()
        Mod.cost = self.cost
        return Mod
    
    def fill_GD(self, GD):
        self.GD = GD.copy_full()
        self.SKS = np.zeros([self.N_pts * self.dim, self.N_pts * self.dim])
    
    def add_cot(self, GD):
        self.GD.add_cot(GD.Cot)
    
    def Compute_SKS_curr(self):
        """
        Supposes that values of GD have been filled
        """
        try:
            x = self.GD.get_points()
            self.SKS = ker.my_K(x, x, self.sig, 0)
            self.SKS += self.nu * np.eye(self.N_pts * self.dim)
        except:
            raise NameError('Need to fill landmark points before computing SKS')
    
    def Compute_SKS(self, x):
        return ker.my_K(x, x, self.sig, 0) + self.nu * np.eye(self.N_pts * self.dim)
    
    def update(self):
        """
        Computes SKS so that it is done only once.
        Supposes that values of GD have been filled
        """
        
        self.Compute_SKS_curr()
    
    def GeodesicControls_curr(self, GDCot):
        """
        Supposes that SKS has been computed and values of GD filled
        Supposes that GDCot has Cot filled
        """
        vs = GDCot.Cot_to_Vs(self.sig)
        vm = vs.Apply(self.GD.get_points(), 0)
        # print(self.sig)
        self.Cont = solve(self.coeff * self.SKS,
                          vm.flatten(), sym_pos=True).reshape(self.N_pts, self.dim)
        self.Mom = self.Cont.copy()
    
    # def GeodesicControls(self, GD, GDCot):
    #    """
    #    Supposes that SKS has been computed and values of GD filled
    #    """
    #    vs = GDCot.Cot_to_Vs(self.sig)
    #    vm = vs.Apply(GD.get_points(), 0)
    #    SKS = self.Compute_SKS(GD)
    #    return solve(self.coeff * SKS,
    #                 vm.flatten(),sym_pos = True).reshape(self.N_pts, self.dim)
    
    def field_generator_curr(self):
        return self.field_generator(self.GD, self.Cont)
    
    def field_generator(self, GD, Cont):
        param = [GD.get_points(), Cont]
        v = old.StructuredFields.StructuredFields_0.StructuredField_0(self.sig, self.dim)
        v.fill_fieldparam(param)
        return v
    
    def Cost_curr(self):
        SKS = self.SKS
        p = self.Cont.flatten()
        self.cost = self.coeff * np.dot(p, np.dot(SKS, p)) / 2
    
    def Cost(self, GD, Cont):
        x = GD.get_points()
        SKS = self.Compute_SKS(x)
        p = Cont.flatten()
        return self.coeff * np.dot(p, np.dot(SKS, p)) / 2
    
    def DerCost_curr(self):  # tested
        vs = self.field_generator_curr()
        der = vs.p_Ximv(vs, 1)
        out = self.GD.copy()
        out.Cot['0'] = [(self.coeff * der['0'][0][1], np.zeros([self.N_pts, self.dim]))]
        return out
    
    def DerCost(self, GD, Mom):  # tested
        vs = self.field_generator(GD, Mom)
        der = vs.p_Ximv(vs, 1)
        out = self.GD.copy()
        out.Cot['0'] = [(self.coeff * der['0'][0][1], np.zeros([self.N_pts, self.dim]))]
        return out
    
    def cot_to_innerprod_curr(self, GDCot, j):  # tested
        """
         Transforms the GD (with Cot filled) GDCot into vsr and computes
         the inner product (or derivative wrt self.GD) with the
         field generated by self.
         The derivative is a returned as a GD with Cot filled (mom=0)
        """
        
        vsr = GDCot.Cot_to_Vs(self.sig)
        v = self.field_generator_curr()
        innerprod = v.p_Ximv(vsr, j)
        
        if j == 0:
            out = innerprod
        if j == 1:
            out = self.GD.copy()
            out.Cot['0'] = [(innerprod['0'][0][1], np.zeros([self.N_pts, self.dim]))]
        
        return out
