class DeformationModule(object):
    """
    Abstract class for deformation module
    
    
    Attributes:
        -- :control h (optional): intensity; parametrization of possible vectors field (of the ambiant space) generated by the current shape
        -- :shape q: geometrical state/descriptor (aka GD); where and how? 
                
                
    Methods: 
        -- GeodesicControls (v_s, q) where v_s is in V^\ast, q a GD, returns the corresponding geodesic control
        -- FieldGenerator (q, h) where m is a GD, h a control. It returns a structured field in V_q \subset V
        -- Cost (q, h) where q is a GD, h a control. It returns the cost (scalar)
        -- DerCost (m, h) where m is a GD, h a control. It returns the derivative of the cost wrt q
        
    For each method, there is a "_curr" version which supposes that GD are 
        known (and necessary functions computes)
    
    """
    
    def add_GD(self, GDCot):
        self.GD.add_GD(GDCot)
    
    def add_tan(self, GDCot):
        self.GD.add_tan(GDCot)
    
    def add_cotan(self, GDCot):
        self.GD.add_cotan(GDCot)
    
    def mult_GD_scal(self, s):
        self.GD.mult_GD_scal(s)
    
    def mult_tan_scal(self, s):
        self.GD.mult_tan_scal(s)
    
    def mult_cotan_scal(self, s):
        self.GD.mult_cotan_scal(s)
    
    def add_speedGD(self, GDCot):
        self.GD.add_speedGD(GDCot)
    
    def sum_GD(self, GD0, GD1):
        self.GD.sum_GD(GD0, GD1)
